let Name = "Ben Ruitenbeek";
let jF = 20;
let sP = "Time Slowdown";
let S = 280;
let B = "Honda VFR VTEC";
let lL = 2;
let A = 2000;
let NoL = 3;
let bP = 100;
let L = 1;
var wanted = false;
console.log("Name: "+ Name);
console.log("JumpForce: "+jF);
console.log("SpecialPower: "+ sP);
console.log("Speed: "+ S);
console.log("Bike: "+ B);
console.log("Lives left: "+ lL);
console.log("Ammo: "+ A);
console.log("NumberOfLasers: "+ NoL);
console.log("BatteryPower"+ bP);
console.log("Level: "+ L);
console.log("Wanted: "+ wanted);